"use client";
import {useMemo,useState} from "react";
import {BadgeCheck,ExternalLink,Link2,Loader2,ReceiptText,Scale,ShieldCheck,Wallet} from "lucide-react";
import {createClient} from "genlayer-js";
import {studionet} from "genlayer-js/chains";
import {TransactionStatus} from "genlayer-js/types";
declare global{interface Window{ethereum?:{request(args:{method:string;params?:unknown[]}):Promise<unknown>}}}
// Studio Next / GenLayer Testnet (chain ID 61997).
// The environment variable remains supported for alternate deployments.
const DEFAULT_CONTRACT=process.env.NEXT_PUBLIC_CONTRACT_ADDRESS??"0x89f972F5E8D015E4fFDF49739cC6da3fB8b9D578";
const readClient=createClient({chain:studionet});
type Receipt={verdict?:string;primary_gap?:string;score?:number|bigint;evidence_quality?:string;observed_current_minor?:number|bigint;observed_reference_minor?:number|bigint;currency?:string;summary?:string;status?:string};
export default function Home(){
 const[account,setAccount]=useState(""),[contract,setContract]=useState(DEFAULT_CONTRACT),[merchant,setMerchant]=useState("store.google.com"),[product,setProduct]=useState("Pixel 10 Pro"),[currency,setCurrency]=useState("USD"),[current,setCurrent]=useState("79900"),[reference,setReference]=useState("99900"),[scope,setScope]=useState("All customers in the United States; no membership requirement."),[sources,setSources]=useState(["https://store.google.com/","https://store.google.com/terms"]),[claimId,setClaimId]=useState("0"),[receiptId,setReceiptId]=useState("0");
 const[receipt,setReceipt]=useState<Receipt|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("Stage an offer, then ask independent validators to inspect the live evidence."),[tx,setTx]=useState("");
 const discount=useMemo(()=>{const a=Number(current),b=Number(reference);return b>a&&b>0?Math.round((b-a)*10000/b):0},[current,reference]),valid=/^0x[a-fA-F0-9]{40}$/.test(contract);
 const wallet=()=>{if(!account||!window.ethereum)throw Error("Connect a wallet first.");return createClient({chain:studionet,account:account as `0x${string}`,provider:window.ethereum as never})};
 async function run(name:string,fn:()=>Promise<void>){setBusy(name);try{await fn()}catch(e){setMessage(e instanceof Error?e.message:"Operation failed.")}finally{setBusy("")}}
 async function connect(){const list=await window.ethereum?.request({method:"eth_requestAccounts"}) as string[]|undefined;if(!list?.[0])throw Error("MetaMask is required.");setAccount(list[0]);setMessage("Wallet connected to GenLayer StudioNet.")}
 async function wait(hash:`0x${string}`){setTx(hash);await readClient.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED})}
 async function create(){if(!valid)throw Error("Enter the deployed PRICEPROOF contract address.");const counts=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}) as(number|bigint)[];const id=Number(counts[0]);const hash=await wallet().writeContract({address:contract as `0x${string}`,functionName:"create_claim",args:[merchant,product,currency,Number(current),Number(reference),discount,scope,JSON.stringify(sources)],value:0n});setMessage("Claim submitted. Waiting for finalization…");await wait(hash);setClaimId(String(id));setMessage(`Offer #${id} is sealed and ready for audit.`)}
 async function audit(){if(!valid)throw Error("Enter a valid contract address.");const counts=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}) as(number|bigint)[];const id=Number(counts[1]);const hash=await wallet().writeContract({address:contract as `0x${string}`,functionName:"audit_claim",args:[Number(claimId)],value:0n});setMessage("Validators are independently checking the live offer…");await wait(hash);setReceiptId(String(id));await load(String(id));setMessage("Consensus finalized the Price Claim Receipt.")}
 async function load(target=receiptId){if(!valid)throw Error("Enter a valid contract address.");const r=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_receipt",args:[Number(target)]}) as Receipt;setReceipt(r);setReceiptId(target)}
 const tone=receipt?.verdict==="VERIFIED"?"ok":receipt?.verdict==="REJECTED"?"bad":"warn";
 return <main className="min-h-screen bg-[#f4f1e8] text-[#161814]"><header className="border-b-2 border-[#161814] bg-[#ff5a36]"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl border-2 border-black bg-[#fff7d6]"><ReceiptText/></span><div><b className="tracking-[.12em]">PRICEPROOF</b><p className="text-sm">Retail claims, cross-examined</p></div></div><button className="action secondary" onClick={()=>run("connect",connect)}><Wallet size={17}/>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></div></header>
 <div className="mx-auto grid max-w-[1500px] gap-5 px-5 py-6 lg:grid-cols-[1.15fr_.85fr]"><section className="panel"><div className="eyebrow"><Scale size={15}/> LIVE OFFER DOCKET</div><h1>Is the discount real?</h1><p className="lead">Freeze the advertised numbers and conditions. Validators reopen the official pages and issue an expiring, challengeable receipt.</p>
 <label>Deployed contract<input value={contract} onChange={e=>setContract(e.target.value.trim())} placeholder="0x…"/></label><div className="grid2"><label>Merchant domain<input value={merchant} onChange={e=>setMerchant(e.target.value)}/></label><label>Product<input value={product} onChange={e=>setProduct(e.target.value)}/></label></div><div className="grid3"><label>Current price · minor units<input inputMode="numeric" value={current} onChange={e=>setCurrent(e.target.value.replace(/\D/g,""))}/></label><label>Reference price<input inputMode="numeric" value={reference} onChange={e=>setReference(e.target.value.replace(/\D/g,""))}/></label><label>Claimed discount<input readOnly value={`${(discount/100).toFixed(2)}%`}/></label></div><div className="grid2"><label>Currency<input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase().slice(0,3))}/></label><label>Audience & conditions<input value={scope} onChange={e=>setScope(e.target.value)}/></label></div>
 <label>Official evidence URLs{sources.map((s,i)=><div className="url" key={i}><Link2 size={17}/><input aria-label={`Source ${i+1}`} value={s} onChange={e=>setSources(old=>old.map((v,j)=>j===i?e.target.value:v))}/></div>)}</label><div className="buttons"><button className="action" disabled={!!busy||!account} onClick={()=>run("create",create)}>{busy==="create"?<Loader2 className="spin"/>:<ShieldCheck/>}Seal offer claim</button><button className="action dark" disabled={!!busy||!account} onClick={()=>run("audit",audit)}>{busy==="audit"?<Loader2 className="spin"/>:<Scale/>}Run consensus audit</button></div></section>
 <aside className="space"><section className="receipt"><div className="receiptTop"><span>PRICE CLAIM RECEIPT</span><strong className={tone}>{receipt?.verdict??"UNAUDITED"}</strong></div><div className="score">{Number(receipt?.score??0)}<small>/100</small></div><div className="facts"><Fact k="Receipt" v={`#${receiptId}`}/><Fact k="Primary gap" v={receipt?.primary_gap??"—"}/><Fact k="Observed" v={receipt?`${Number(receipt.observed_current_minor??0)} ${receipt.currency??""}`:"—"}/><Fact k="Reference" v={receipt?`${Number(receipt.observed_reference_minor??0)} ${receipt.currency??""}`:"—"}/><Fact k="Evidence" v={receipt?.evidence_quality??"—"}/><Fact k="Status" v={receipt?.status??"—"}/></div><p className="summary">{receipt?.summary??"No receipt has been loaded. Consensus evidence will appear here without hiding qualifications."}</p><div className="load"><input value={receiptId} onChange={e=>setReceiptId(e.target.value.replace(/\D/g,""))}/><button onClick={()=>run("load",()=>load())}>Load receipt</button></div></section>
 <section className="note"><BadgeCheck/><div><b>Fail-closed by design</b><p>Verdict, gap, currency and observed prices must match. Scores stay within ±10 and the same band.</p></div></section><section className="status"><b>Protocol status</b><p>{message}</p>{tx&&<a href={`https://explorer-studio.genlayer.com/tx/${tx}`} target="_blank" rel="noreferrer">Open transaction <ExternalLink size={14}/></a>}</section></aside></div><footer>Not a price feed. A versioned adjudication record for a precisely scoped retail claim.</footer></main>
}
function Fact({k,v}:{k:string;v:string}){return <div><span>{k}</span><b>{v}</b></div>}
